app_name: '公式アカにリプライ飛ばす奴をブロックする奴'
app_name_short: 'ブロック奴'
app_version: "1.0.1"
page_description: 'Twitterで公式アカウントなどにリプライを送っている人を検索してまとめてブロックするツールです'
page_keywords: 'Twitter ブロック 公式アカウント リプライ'

twitter_page:  'https://twitter.com/'
facebook_page: 'https://www.facebook.com/'
github_page:   'https://github.com/'
